### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by ThorvaldAagaard** [Jauhen/EasyBridge#6]
As a lot of others I have had a go at downloading EasyBridge from Steven Han's site, and after playing around with MS Visual C++ i decided to make sure the solution can run on more recent Visual Studio platforms.

I ended up with a linker error, and in the search for a solution I found your Github, and realised that you had done the work and even added test. Well Done

But after cloning your repository and downloading that I got this error

LINK : fatal error LNK1104: cannot open file 'gmock.lib'

So it is probably because the t2 lib-files from Google Test are not included in the Visual Studio solution

Will you add those?

**Comment by ThorvaldAagaard** [comment]
Ok, after building the individual projects the lib-files are generated from the gmock and gtest projects

**Comment by NormR** [comment]
My changes to Hans's EB program are posted on this site: https://sites.google.com/site/normsstuff1/

There is another site that has also updated EB: https://github.com/azureskydiver/EasyBridge
